apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: movie-app
spec:
  capacity:
    storage: 10Gi 
  accessModes:
    - ReadWriteOnce
  hostPath: 
    path: /mnt/data/postgres
